export enum ActionType {
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  INCREMENT_ITEM = "INCREMENT_ITEM",
  DECREMENT_ITEM = "DECREMENT_ITEM",
  INITIALIZE_STORE = "INITIALIZE_STORE",
  SET_CURRENCY = "SET_CURRENCY",
}
